version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - ./inventario.db:/app/inventario.db
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python3 -m flask run --host=0.0.0.0 --port=5001
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm start
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  node_modules:
