services:
  # Frontend (React) - Solo el frontend por ahora
  - type: web
    name: inventario-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://inventario-backend.onrender.com
